<script>


    function customPromise(executor) {
        let onResolve, onReject, isCalled = false,
            isFulfilled = false, isRejected = false, output, err;

        // Then function for handling successfull promise execution
        this.then = function(resolveCallback) {
            // Storing resolve callback function
            onResolve = resolveCallback;

            // Check if the promise has not yet resolved/rejected and executor isFulfilled
            if(!isCalled && isFulfilled) {
                // Mark the promise as resolved
                isCalled = true;
                onResolve(output);
            }
            // Returning this to enable chaining of then
            return this;
        }

        // Catch function for handling errors in promise execution
        this.catch = function(rejectCallback) {
            // Storing reject callback function
            onReject = rejectCallback;

            // Check if the promise has not yet resolved/rejected and executor isRejected
            if(!isCalled && isRejected) {
                // Mark the promise as rejected
                isCalled = true;
                onReject(err);
            }
            // Returning this to enable chaining of catch
            return this;
        }

        // Resolver function
        function resolver(data) {
            // Mark the isFulfilled flag as true since the executor work isFulfilled
            // and store result in output
            isFulfilled = true;
            output = data;

            // Calling the resolve function with data
            if(typeof onResolve=== 'function' && !isCalled){
                isCalled = true;
                onResolve(data);
            }
        }

        // Rejecter function
        function rejecter(error) {
            // Mark the isRejected flag as true since the executor work isFulfilled
            // and store result in output
            isRejected = true;
            err = error;

            // Calling the reject function with error
            if(typeof onReject === 'function' && !isCalled){
                isCalled = true;
                onReject(error);
            }
        }

        // Calling the executor function with resolver and rejecter
        executor(resolver, rejecter);
    }

let p1 = new customPromise(
(resolve, reject) => setTimeout(() => resolve('Resolved successfully', 1000))
);
p1.then((data) => console.log(data));
// Output - Resolved successfully

let p2 = new customPromise(
(resolve, reject) => resolve('Resolved right away');
);
p2.then((data) => console.log(data));
// Output - Resolved right away

</script>